all:
  vars:
    tftpd_netboot_xyz_enable: true
    httpboot_netboot_xyz_enable: true
  children:
    sh:
      hosts:
        nrt1sh1.tun.y2e.org:
          ansible_host: 192.168.30.218
          ansible_connection: ssh
          ansible_ssh_user: root
          keepalived_interface: eth1
          keepalived_interface_ivn: eth2

        ttj1sh1.tun.y2e.org:
          ansible_host: 192.168.30.215
          ansible_connection: ssh
          ansible_ssh_user: root
          keepalived_interface: eth1
          keepalived_interface_ivn: dummy

        hnd3sh1.tun.y2e.org:
          ansible_host: 192.168.30.223
          ansible_connection: ssh
          ansible_ssh_user: root
          keepalived_interface: tap_tun
          keepalived_interface_ivn: dummy
