services:
  ntp:
    image: dockurr/chrony
    environment:
      NTP_SERVERS: "time.cloudflare.com"
    ports:
      - "192.168.31.100:123:123/udp"
      - "192.168.30.100:123:123/udp"
    restart: always
