---
- name: Upgrade all packages
  hosts: [sh, tun.sh, hv]
  tasks:
    - name: Update APT package index
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade installed packages
      ansible.builtin.apt:
        upgrade: 'yes'

    - name: Perform distribution upgrade
      ansible.builtin.apt:
        upgrade: dist

    - name: Remove unnecessary packages
      ansible.builtin.apt:
        autoremove: true
